**K-Fold cross validation**

In [5]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier

import numpy as np
from sklearn.datasets import load_digits

In [3]:
digits = load_digits(as_frame=True)
dir(digits)

['DESCR', 'data', 'feature_names', 'frame', 'images', 'target', 'target_names']

In [21]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [22]:
lr = LogisticRegression()
lr.fit(X_train, y_train)
lr.score(X_test, y_test)

/opt/anaconda3/envs/dsai/lib/python3.13/site-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9648148148148148

In [23]:
svm = SVC()
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

0.9925925925925926

In [24]:
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

0.975925925925926

In [28]:
from sklearn.model_selection import KFold

kfold = KFold(n_splits=5)



In [29]:
for train_index, test_index in kfold.split(range(1, 11)):
    print(train_index, test_index)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


In [30]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

In [31]:
get_score(rf, X_train, X_test, y_train, y_test)

0.9777777777777777

In [34]:
from sklearn.model_selection import StratifiedKFold

folds = StratifiedKFold(n_splits=3)

In [44]:
digits.data.iloc[2]

pixel_0_0     0.0
pixel_0_1     0.0
pixel_0_2     0.0
pixel_0_3     4.0
pixel_0_4    15.0
             ... 
pixel_7_3     3.0
pixel_7_4    11.0
pixel_7_5    16.0
pixel_7_6     9.0
pixel_7_7     0.0
Name: 2, Length: 64, dtype: float64

In [53]:
scores_l = []
scores_svm = []
scores_rf = []

for train_index, test_index in kfold.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data.iloc[train_index], digits.data.iloc[train_index], digits.target.iloc[train_index], digits.target.iloc[test_index]
    # print("Logistic regression", get_score(LogisticRegression(), X_train, X_test, y_train, y_test))
    print(len(train_index), len(test_index))
    

1437 360
1437 360
1438 359
1438 359
1438 359
